Repository FOSSRIT/fossrit.github.io, pull requests merged in 2019-10, with the labels that each got.

#53 announcements: Add RMF call for participation
  announcements/_posts/2019-10-03-rochester-maker-faire.md
Labels: announcement

#54 Create event for The Future is Open 2019
  events/_posts/2019-10-26-the-future-is-open.md
Labels: content, new change

#57 Publish final draft of The Future is Open 2019 schedule
  events/_posts/2019-10-26-the-future-is-open.md
Labels: content, new change

#58 dependencies: Fix nokogiri CVE by updating dependencies
  Gemfile
  Gemfile.lock
Labels: bug

#61 Fix syntax error
  events/_posts/2019-10-26-the-future-is-open.md
Labels: bug, content

#62 Nicer schedule
  events/_posts/2019-10-26-the-future-is-open.md
Labels: content, improvement

#63 Future is Open: Update schedule, fix typos
  events/_posts/2019-10-26-the-future-is-open.md
Labels: content, improvement

#64 FIO: Add Nando Ellis to alum panel
  events/_posts/2019-10-26-the-future-is-open.md
Labels: content, improvement

#65 FIO: "Alumni Panel" -> "Alum Panel" for inclusivity
  events/_posts/2019-10-26-the-future-is-open.md
Labels: content, improvement

#66 FIO: Add Nando Ellis to speakers page
  events/_posts/2019-10-26-the-future-is-open.md
Labels: content, improvement

#67 FIO: Add "Tracking the impact of zoo conservation" from Tom Snyder
  events/_posts/2019-10-26-the-future-is-open.md
Labels: content, new change

#73 FIO: Add photos to event page gallery
  events/_posts/2019-10-26-the-future-is-open.md
  events/assets/2019/10/fio-balcony-view.jpg
  events/assets/2019/10/fio-lunch-break.jpg
  events/assets/2019/10/fio-panel-discussion.jpg
  events/assets/2019/10/fio-red-hat-swag.jpg
  events/assets/2019/10/fio-tim-zabel-tigeros.jpg
Labels: content, improvement
