Repository FOSSRIT/fossrit.github.io, pull requests merged in 2020-04, with the labels that each got.

#138 Update calendar for virtual FOSS Hours
  meetings-meetups/_posts/2020-01-16-foss-hours.md
  meetings-meetups/_posts/2020-03-26-virtual-foss-hours.md
Labels: improvement, type - content

#140 librecorps: Add suggested SJ edits
  librecorps.md
Labels: improvement, type - content

#142 config: Generate a sitemap and highlight it in robots.txt
  _config.yml
  robots.txt
Labels: new change

#145 Add dropdown to navbar
  Rakefile
  _data/tabs.yml
  _includes/layout/header.html
Labels: improvement

#144 seo-meta: Add meta tag for Google Search Console verification
  _includes/layout/seo-meta.html
Labels: new change

#147 Add new "Open@RIT" page to track ongoing work (closes #146)
  _data/tabs.yml
  open-rit.md
Labels: new change, type - content

#148 Add FOSSRIT People/Profiles link to site navbar
  Rakefile
  _data/tabs.yml
Labels: improvement

#152 calendar: Do not include calendar pages in sitemap
  meetings-meetups/_posts/2020-01-16-foss-hours.md
  meetings-meetups/_posts/2020-03-26-virtual-foss-hours.md
  robots.txt
Labels: bug

#149 index: Refresh "Do/Discuss" columns for 2020
  _config.yml
  index.html
Labels: improvement, type - content

#154 announcement: Add Summer FOSS Hours announcement with links
  announcements/_posts/2020-04-28-summer-foss-hours.md
Labels: new change, type - announcement

#153 about/footer: Add link to FOSS@RIT Runbook (closes #143)
  _data/footer/rit.yml
  about.md
Labels: improvement, type - announcement
