Repository FOSSRIT/fossrit.github.io, pull requests merged in 2020-03, with the labels that each got.

#91 Add "White House Champions of Change" event, from @decause
  events/_posts/2013-07-23-white-house-champions-change.md
Labels: new change, type - content

#102 events: Fix URL, adjust formatting for ENH 2010
  events/_posts/2010-11-04-election-night-hackathon.md
Labels: improvement, type - content

#104 projects: Add ZeroQuest
  projects/_posts/2015-12-12-zeroquest.md
  projects/assets/zeroquest.png
Labels: new change, type - content

#103 projects: Add AngleGators
  projects/_posts/2015-05-20-anglegators.md
  projects/assets/anglegators.png
Labels: new change, type - content

#105 projects: Add LZR
  projects/_posts/2018-07-14-lzr.md
  projects/assets/lzr/lzr-cover.jpg
  projects/assets/lzr/lzr-fedora1.jpg
  projects/assets/lzr/lzr-fedora2.jpg
  projects/assets/lzr/lzr1.jpg
  projects/assets/lzr/lzr2.jpg
  projects/assets/lzr/lzr3.jpg
  projects/assets/lzr/lzr4.jpg
  projects/assets/lzr/lzr5.jpg
Labels: new change, type - content

#106 projects: Add LearnIt by @wilfriedE
  projects/_posts/2017-11-18-learnit.md
  projects/assets/learnit/learnit-content.jpg
  projects/assets/learnit/learnit-cover.jpg
Labels: new change, type - content

#107 projects: Add PyCut
  projects/_posts/2017-01-20-pycut.md
  projects/assets/pycut/pycut-game.png
  projects/assets/pycut/pycut-help.png
Labels: new change, type - content

#108 projects: Add Fractionauts
  projects/_posts/2014-06-05-fractionauts.md
  projects/assets/fractionauts.png
Labels: new change, type - content

#110 events: Add picture of SkyTime in the White House
  events/_posts/2013-07-23-white-house-champions-change.md
  events/assets/2013/07/skytime-in-white-house.png
Labels: improvement, type - content

#112 projects: Update TigerOS year and project repositories
  projects/_posts/2019-12-31-tigeros.html
Labels: improvement, type - content

#109 projects: Add SkyTime
  projects/_posts/2013-09-10-skytime.md
  projects/assets/skytime/skytime-gameplay1.gif
  projects/assets/skytime/skytime-gameplay2.gif
  projects/assets/skytime/skytime-gameplay3.gif
  projects/assets/skytime/skytime-gameplay4.gif
  projects/assets/skytime/skytime-lemonade-day-2013.png
  projects/assets/skytime/skytime-logo.png
  projects/assets/skytime/skytime-start.gif
  projects/assets/skytime/skytime-stem-camp.png
Labels: new change, type - content

#111 projects: Update TeleIRC for 2020
  projects/_posts/2018-01-01-teleirc.md
  projects/_posts/2020-03-01-teleirc.md
Labels: improvement, type - content

#116 about: Fix link to FOSS Minor curriculum
  about.md
Labels: bug, type - content

#114 Add Travis CI gated deployments (closes #44)
  .travis.yml
  README.md
  _config.yml
Labels: new change, quality assurance

#85 Add Calendar page
  calendar.html
  feeds/calendar.ics
  meetings-meetups/_posts/2020-01-16-foss-hours.md
Labels: new change

#121 calendar: Remove summary prefix logic
  calendar.html
Labels: improvement

#120 ci: Build and deploy to gh-pages branch (closes #119)
  .travis.yml
Labels: improvement, quality assurance

#124 announcement: Add call for Imagine RIT 2020 projects
  announcements/_posts/2020-03-11-call-for-imagine-2020-projects.md
Labels: new change, type - announcement

#122 events: Add Software Freedom Day 2015
  events/_posts/2015-09-19-software-freedom-day.md
  events/assets/2015/09/sfd-2015-badge-winners.jpg
  events/assets/2015/09/sfd-2015-group.jpg
  events/assets/2015/09/sfd-2015-table.jpg
Labels: new change, type - content

#126 events: Add picture of @decause teaching at BrickHack 2016
  events/_posts/2016-03-05-brickhack.md
  events/assets/2016/03/brickhack-2016-decause-teaching.jpg
Labels: improvement, type - content

#127 announcements: Imagine RIT 2020 is canceled
  announcements/_posts/2020-03-11-call-for-imagine-2020-projects.md
Labels: new change, type - content

#125 ci: Run tests with Rakefile, cache html-proofer data
  .travis.yml
  Gemfile
  Gemfile.lock
  Rakefile
Labels: improvement, quality assurance

#128 announcement: Virtual FOSS Hours!
  announcements/_posts/2020-03-18-virtual-foss-hours.md
Labels: new change, type - announcement

#130 projects: Add Fortune Hunter project profile
  projects/_posts/2010-02-21-fortune-hunter.md
  projects/assets/fortune-hunter.png
Labels: new change, type - content

#131 projects: Add Lemonade Stand OLPC XO game
  projects/_posts/2010-11-12-lemonade-stand.md
  projects/assets/lemonade-stand/lemonade-stand-1.jpg
  projects/assets/lemonade-stand/lemonade-stand-2.png
  projects/assets/lemonade-stand/lemonade-stand-3.jpg
Labels: new change, type - content

#132 projects: Add Open Video Chat project profile
  projects/_posts/2010-08-17-open-video-chat.md
  projects/assets/open-video-chat/open-video-chat-1.png
  projects/assets/open-video-chat/open-video-chat-2.jpg
Labels: new change, type - content

#133 projects: Add Blocku project profile
  projects/_posts/2011-02-22-blocku.md
  projects/assets/blocku/blocku-logo.png
  projects/assets/blocku/blocku-title-screen.png
  projects/assets/blocku/blocku-tutorial.gif
  projects/assets/blocku/blocku-win.png
Labels: new change, type - content

#134 projects: Add CIVX.us project profile
  projects/_posts/2011-08-30-civx.md
  projects/assets/civx.jpg
Labels: new change, type - content

#129 gitignore: Cover more tools and editors
  .gitignore
Labels: contributor experience, improvement

#135 ci: Revert Travis deploy pipeline
  .travis.yml
Labels: improvement, quality assurance

#137 Dependency bump to fix Jekyll builds
  Gemfile.lock
Labels: bug, dependencies, quality assurance

#136 librecorps: Add link to Resources site
  librecorps.md
Labels: new change, type - content
